project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView

from apps.cadre import views as vcadre

from apps.cadre.views import EmployeeListView, EmployeeDetail

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^employee/(?P<pk>[0-9]+)/$', vcadre.EmployeeDetail.as_view()),
    url(r'^employees/', vcadre.EmployeeListView.as_view()),
    url(r'^persons/', vcadre.PersonGroupedListView.as_view()),
]

apps/cadre/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Departament(models.Model):
	title = models.TextField('Название', max_length=255)

	class Meta:
		verbose_name = 'Отдел'
		verbose_name_plural = 'Отделы'
		ordering = ['title']

	def __str__(self):
		return self.title


class Post(models.Model):
	title = models.TextField('Название', max_length=255)

	class Meta:
		verbose_name = 'Должность'
		verbose_name_plural = 'Должности'
		ordering = ['title']

	def __str__(self):
		return self.title


class Person(models.Model):
	"""в задаче не было условий управлять полномочиями пользователями,
	потому просто создадим модель с нуля с нужными полями а не будем наследоваться
	от AbstractUser"""
	first_name = models.CharField('Имя', max_length=30)
	middle_name = models.CharField('Отчество', max_length=30, null=True, blank=True)
	last_name = models.CharField('Фамилия', max_length=50)
	birth_date = models.DateTimeField('Дата рождения')
	email = models.EmailField('Email', unique=True)
	phone = models.CharField('Телефон', max_length=15, null=True, blank=True)

	class Meta:
		verbose_name = 'Карточка'
		verbose_name_plural = 'Карточки'
		ordering = ['last_name']

	def __str__(self):
		full_name = '%s %s. %s.' % (self.last_name, self.first_name[:1], self.middle_name[:1])
		return full_name

	def get_full_name(self):
		full_name = '%s %s %s' % (self.last_name, self.first_name, self.middle_name)
		return full_name.strip()


class Employee(models.Model):
	person = models.ForeignKey(Person)
	departament = models.ForeignKey(Departament)
	post = models.ForeignKey(Post)
	date_joined = models.DateTimeField('Дата начала работы', auto_now_add=True)
	date_fired = models.DateTimeField('Дата окончания работы', null=True, blank=True)

	class Meta:
		verbose_name = 'Сотрудник'
		verbose_name_plural = 'Сотрудники'
		ordering = ['id']

	def __str__(self):
		return self.person.get_full_name()

project/templates/base.html
{% load staticfiles %}
<html>
  <head>
    <title>Кадры</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

project/templates/employee_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<h1>Карточка сотрудника</h1>
	<div class="row">
		<div class="col-md-2">Сотрудник</div>
		<div>{{ object }}</div>
	</div>
	<div class="row">
		<div class="col-md-2">Дата рождения</div>
		<div>{{ object.person.birth_date|date:"j E Y" }}</div>
	</div>
	<div class="row">
		<div class="col-md-2">email</div>
		<div>{{ object.person.email }}</div>
	</div>
	<div class="row">
		<div class="col-md-2">Контактный телефон</div>
		<div>{{ object.person.phone }}</div>
	</div>

	<div class="row">
		<div class="col-md-2">Подразделение</div>
		<div>{{ object.departament }}</div>
	</div>
	<div class="row">
		<div class="col-md-2">Должность</div>
		<div>{{ object.post }}</div>
	</div>
	<div class="row">
		<div class="col-md-2">Принят на работу</div>
		<div>{{ object.date_joined|date:"j E Y" }}</div>
	</div>
	<div class="row">
	{% if object.date_fired %}
		<div class="col-md-2">Уволен</div>
		<div>{{ object.date_fired|date:"j E Y" }}</div>
	{% else %}
		<div class="col-md-12">Действующий сотрудник</div>
	{% endif %}
	</div>
</div>
{% endblock %}

project/templates/employee_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<div class="text-center"><a href="/">На главную</a></div>
	<h1 class="text-center">Кадровый состав</h1>
	<div class="row">
		<div class="col-md-offset-3 col-md-3">
			<div class="row">
				<div>Отдел:</div>
				<div class="dropdown">
				  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
				  	{% if departament %}
				    {{ departament.title }}
				    {% else %}
				    Все
				    {% endif %}
				    <span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
				    <li><a href="{{ request.path }}{% if is_employee %}?is_employee={{ is_employee }}&{% endif %}">Все</a></li>
				    <li role="separator" class="divider"></li>
				    {% for d in departament_list %}
				    <li><a href="{{ request.path }}?{% if is_employee %}is_employee={{ is_employee }}&{% endif %}departament={{ d.id }}">{{ d.title }}</a></li>
				    {% endfor %}
				  </ul>
				</div>
			</div>			
		</div>
		<div class="col-md-3">
			<div class="row">
				<div>Сотрудник?</div>
				<div class="dropdown">
				  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
				  	{% if not is_employee %}
				    Все
				    {% elif is_employee == "1" %}
				    Работает в компании
				    {% else %}
				    Не работает в компании
				    {% endif %}
				    <span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
				    <li><a href="{{ request.path }}{% if departament %}?departament={{ departament.id }}&{% endif %}">Все</a></li>
				    <li role="separator" class="divider"></li>
				    <li><a href="{{ request.path }}?{% if departament %}departament={{ departament.id }}&{% endif %}is_employee=1">Работает в компании</a></li>
				    <li><a href="{{ request.path }}?{% if departament %}departament={{ departament.id }}&{% endif %}is_employee=0">Не работает в компании</a></li>
				  </ul>
				</div>
			</div>
		</div>
	</div>

	<table class="table">
		<thead>
			<tr class="row">
		  	<th class="col-md-3">Сотрудник</th>
	  		<th class="col-md-3">Подразделение</th>
	  	</tr>
	  </thead>
	  <tbody>
		  {% for empl in employee_list %}
		  <tr class="row">
		    <td class="col-md-3"><a href="/employee/{{ empl.id }}/" target="_blank">{{ empl.person }}</a></td>
		    <td class="col-md-3">{% if empl.date_fired %}-{% else %}{{ empl.departament }}{% endif %}</td>
		  </tr>
		  {% endfor %}
		</tbody>
  </table>

  {% if is_paginated %}
	<nav aria-label="Page navigation">
		<div class="row row-centered">
			<div class="col-centered">
		  <ul class="pagination">
	      {% if page_obj.has_previous %}
		    <li>
		      <a href="?{% if departament %}departament={{ departament.id }}&{% endif %}{% if is_employee %}is_employee={{ is_employee }}&{% endif %}page={{ page_obj.previous_page_number }}" aria-label="Предыдущая">
		        <span aria-hidden="true">&laquo;</span>
		      </a>
		    </li>
	      {% endif %}
		    <li><a href="#">{{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a></li>
	      {% if page_obj.has_next %}
		    <li>
		      <a href="?{% if departament %}departament={{ departament.id }}&{% endif %}{% if is_employee %}is_employee={{ is_employee }}&{% endif %}page={{ page_obj.next_page_number }}" aria-label="Следующая">
		        <span aria-hidden="true">&raquo;</span>
		      </a>
		    </li>
	      {% endif %}
		  </ul>
		  </div>
	  </div>
	</nav>
  {% endif %}
</div>
{% endblock %}

project/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container text-center">
	<div><a href="/employees/">Список работников с фильтрами</a></div>
	<div><a href="/persons/">Список фамилий</a></div>
</div>
{% endblock %}

project/templates/person_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<div class="text-center"><a href="/">На главную</a></div>
	<h1 class="text-center">Справочник фамилий</h1>

	<style>
		.navbar .navbar-nav {
		  display: inline-block;
		  float: none;
		  vertical-align: top;
		}

		.navbar .navbar-collapse {
		  text-align: center;
		}
	</style>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	    </div>

	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	      	{% if filter %}
	        <li><a href="?">Все</a></li>
	        {% else %}
	        <li class="active"><a href="?">Все <span class="sr-only">(current)</span></a></li>
	        {% endif %}
	        {% for filter_item in filter_list %}
	        	{% if filter == filter_item.value %}
		        <li class="active"><a href="?filter={{ filter_item.value }}">{{ filter_item.label }} <span class="sr-only">(current)</span></a></li>
	        	{% else %}
		        <li><a href="?filter={{ filter_item.value }}">{{ filter_item.label }}</a></li>
	        	{% endif %}
	        {% endfor %}
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

	<table class="table">
		<thead>
			<tr class="row">
		  	<th class="col-md-3">Фамилия</th>
	  	</tr>
	  </thead>
	  <tbody>
		  {% for person in object_list %}
		  <tr class="row">
		    <td class="col-md-3">{{ person.last_name }}</td>
		  </tr>
		  {% endfor %}
		</tbody>
  </table>
</div>
{% endblock %}